// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxHIuo8vFUm2ZYSIaYYAG_YXCXjwv75Ew',
    appId: '1:512023527657:web:57fd13882af968f5f07078',
    messagingSenderId: '512023527657',
    projectId: 'fishingguideapp-1a98d',
    authDomain: 'fishingguideapp-1a98d.firebaseapp.com',
    storageBucket: 'fishingguideapp-1a98d.firebasestorage.app',
    measurementId: 'G-J8LT8KZB4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZjfudF1p1CeDsnTOyGcEkWdiYU3Dl1J0',
    appId: '1:512023527657:android:2a195fcde46693d6f07078',
    messagingSenderId: '512023527657',
    projectId: 'fishingguideapp-1a98d',
    storageBucket: 'fishingguideapp-1a98d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVBTIfbW5oE_sGMwMjw_eN8YZEYavBaLQ',
    appId: '1:512023527657:ios:5984cc1a69b0d183f07078',
    messagingSenderId: '512023527657',
    projectId: 'fishingguideapp-1a98d',
    storageBucket: 'fishingguideapp-1a98d.firebasestorage.app',
    iosBundleId: 'com.example.fishingGuideApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVBTIfbW5oE_sGMwMjw_eN8YZEYavBaLQ',
    appId: '1:512023527657:ios:5984cc1a69b0d183f07078',
    messagingSenderId: '512023527657',
    projectId: 'fishingguideapp-1a98d',
    storageBucket: 'fishingguideapp-1a98d.firebasestorage.app',
    iosBundleId: 'com.example.fishingGuideApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxHIuo8vFUm2ZYSIaYYAG_YXCXjwv75Ew',
    appId: '1:512023527657:web:9381d6c8a071523df07078',
    messagingSenderId: '512023527657',
    projectId: 'fishingguideapp-1a98d',
    authDomain: 'fishingguideapp-1a98d.firebaseapp.com',
    storageBucket: 'fishingguideapp-1a98d.firebasestorage.app',
    measurementId: 'G-H9C3NVZGST',
  );
}
